//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS_Inquire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 医务人员信息表
    {
        public int 编号 { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public string 所属科室 { get; set; }
        public string 专业职务 { get; set; }
        public string 学历 { get; set; }
        public string 出生日期 { get; set; }
        public string 名族 { get; set; }
        public string 政治面貌 { get; set; }
        public string 从医经历 { get; set; }
        public string 婚姻状况 { get; set; }
        public string 科室电话 { get; set; }
    }
}
