//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS_Inquire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 医疗设备信息表
    {
        public int 注册编号 { get; set; }
        public string 设备名称 { get; set; }
        public string 规格 { get; set; }
        public string 所属科室 { get; set; }
        public string 生产日期 { get; set; }
        public string 生产厂商 { get; set; }
        public string 维修记录 { get; set; }
        public string 维修负责人 { get; set; }
    }
}
