//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS_Inquire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 诊疗方案信息表
    {
        public int 病目编号 { get; set; }
        public string 疾病名称 { get; set; }
        public string 典型症状 { get; set; }
        public string 致病原因 { get; set; }
        public string 一般治疗手段 { get; set; }
        public string 治疗周期 { get; set; }
        public string 治疗大致费用 { get; set; }
        public string 治疗效果 { get; set; }
        public string 注意事项 { get; set; }
    }
}
